# Part 4: Exploratory data analysis
The exploratory data analysis comprised both a univariate and bivariate examination of the variables.

## Univariate Analysis


## Bivariate Analysis
### Dependent Variable
As mentioned above, the first objective was to identify an available variable that would proxy for box office success. Correlation tests were conducted between the quantitative variables and the log of daily box office revenue. The variables most highly correlated with log of daily box office revenue are summarized in
`r kfigr::figr(label = "correlation1", prefix = TRUE, link = TRUE, type="Table")`.

`r kfigr::figr(label = "correlation1", prefix = TRUE, link = TRUE, type="Table")`: Variables most highly correlated with the log daily box office revenue
```{r correlation1}
mData <- process(train, stage = "a", y = c("daily_box_office_log"))
cData <- correlate(x = mData$numeric, y = mData$dependent, yLab = "Log Daily Box Office", plot = FALSE)
knitr::kable(head(cData$tests, 10), digits = 2) %>%
  kableExtra::kable_styling(bootstrap_options = c("hover", "condensed", "responsive"), full_width = T, position = "center")
```

In the next section, a simple linear regression model was used to determine the parameters required to predict the daily box office proxy variable.


* * *
