---
title: "Movie Rating Model and Predictor"
author: "John James jjames@datasciencesalon.org"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  rmdformats::readthedown:
    highlight: kate
    css: rmdStyles.css
bibliography: library.bib
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r knitr_init, echo=FALSE, cache=FALSE, warning=FALSE, message=FALSE}
options(knitr.table.format = "html")
options(max.print=100, scipen=999, width = 800)
knitr::opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
	             eval = TRUE,
               tidy=TRUE,
               root.dir = "..",
               fig.height = 8,
               fig.width = 20,
               comment=NA,
               message=FALSE,
               warning=FALSE)
knitr::opts_knit$set(width=100, figr.prefix = T, figr.link = T)
knitr::knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=",")
})
```

```{r load-libraries}
library(dplyr)
library(extrafont)
library(ggplot2)
```

```{r source-functions}
source("../R/analysis.R")
source("../R/associate.R")
source("../R/back.R")
source("../R/comparePredictions.R")
source("../R/conclusion.R")
source("../R/correlate.R")
source("../R/createDependent.R")
source("../R/forward.R")
source("../R/prediction.R")
source("../R/preprocess.R")
source("../R/process.R")
source("../R/regressionAnalysis.R")
source("../R/slr.R")
source("../R/univariate.R")
source("../R/univariateQual.R")
source("../R/univariateQuant.R")
source("../R/visualization.R")
```


```{r restore-data}
fin1 <- openxlsx::read.xlsx(xlsxFile = "../data/sample.xlsx")
fin2 <- openxlsx::read.xlsx(xlsxFile = "../data/financials.xlsx")
save(fin1, file = "../data/fin1.Rdata")
save(fin2, file = "../data/fin2.Rdata")
```


```{r load-data}
rerun <- TRUE
load("../data/movies.Rdata")
load("../data/fin1.Rdata")
load("../data/fin2.Rdata")
```

```{r preprocess}
# dataSets  <- preprocess(movies, fin1, fin2)
# train <- dataSets$train
# test <- dataSets$test
# case <- dataSets$case
# mdb2 <- dataSets$mdb2
# save(train, file = "../data/train.RData")
# save(test, file = "../data/test.RData")
# save(case, file = "../data/case.RData")
# save(mdb2, file = "../data/mdb2.RData")
# rerun <- TRUE
```


```{r univariate}
load("../data/train.Rdata")
load("../data/test.Rdata")
load("../data/case.Rdata")
load("../data/mdb2.Rdata")
edaUni <- univariate(mdb = train)
```


```{r model, child = '5.model.rmd'}
```


# References
